---
- name: Setup system, add repository, install package, configure firewall, and remove user
  hosts: all
  become: yes
  vars:
    user: "temp-user"
    apt_repository: "http://aptrepo.srv.cs.cmu.edu"
    # apt_repository: "deb http://aptrepo.srv.cs.cmu.edu stable main"
    package_name: "cmucs-sca-gs"
    iptable_rules:
      - rule: "-A INPUT -s 128.2.0.0/16 --dport 3000 -j ACCEPT"
      - rule: "-A INPUT -s 172.31.0.0/16 --dport 3000 -j ACCEPT"
      - rule: "-A INPUT --dport 3000 -j REJECT --reject-with icmp-port-unreachable"

  tasks:
    - name: Add the apt repository
      apt_repository:
        repo: "deb {{ apt_repository }} $(lsb_release -sc) main"
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install cmucs-sca-gs package   # this is the name assigned to this ansible task, explaining what the task does
      apt:                                 # this is the module use by ansible to manage package on Debian systems like Ubuntu
        name: "{{ package_name }}"         # This is an argument for the apt module, defining a package name to be managed
        state: present                     # this is the second argument of apt module. It determines the desired state of the package

    - name: Add IP table rules
      iptables:
        ipversion: 4
        name: "filter"
        chain: INPUT
        state: present
        rules: "{{ item.rule }}"
      loop: "{{ iptable_rules }}"

    - name: Remove temp-user
      user:
        name: "{{ user }}"
        state: absent
        remove: yes

    - name: Reboot the system
      reboot:
        msg: "Reboot initiated by Ansible playbook after setup."
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 5
        post_reboot_delay: 30
        test_command: "whoami"

# command to execute the playbook : ansible-playbook -i inventory.txt cmu-playbook.yaml
